# @package _global_

dataset:
  view_sampler:
    num_context_views: 100
    num_target_views: 4
    min_distance_between_context_views: 25
    max_distance_between_context_views: 50
    min_distance_to_context_views: 0
    initial_min_distance_between_context_views: 15
    initial_max_distance_between_context_views: 25
    # index_path: assets/evaluation_index_scannet_gauss.json

