defaults:
  - view_sampler: bounded

name: scannet
make_baseline_1: false
augment: true

image_shape: [180, 320]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: true

baseline_epsilon: 1e-3
max_fov: 100.0
load_depth: true
